exports.USER_REQUEST = "USER_REQUEST";
exports.USER_SUCCESS = "USER_SUCCESS";
exports.USER_SUCCESS_USER = "USER_SUCCESS_USER";
exports.USER_SUCCESS_ADMIN = "USER_SUCCESS_ADMIN";
exports.USER_FAIL = "USER_FAIL";

exports.USER_REQUEST_CLEAR = "USER_REQUEST_CLEAR";